# Generated by Django 5.2.6 on 2025-09-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('hora_prestamo', models.TimeField(auto_now_add=True)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('hora_devolucion', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
