# Generated by Django 5.2.6 on 2025-09-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autores', '0001_initial'),
        ('categorias', '0001_initial'),
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_libro', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('nombre_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autores.autor')),
                ('nombre_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('nombre_editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editoriales.editorial')),
            ],
        ),
    ]
