# Generated by Django 5.2.6 on 2025-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('nombre_empleado', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
