# Generated by Django 5.2.6 on 2025-09-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, db_column='nombre_editorial')),
                ('pais', models.CharField(max_length=50, db_column='pais_editorial')),
                ('calle', models.CharField(max_length=100, null=True, db_column='calle_editorial')),
                ('numero_calle', models.IntegerField(null=True, db_column='numero_calle_editorial')),
                ('casa', models.BooleanField(default=False, db_column='casa_editorial')),
                ('edificio', models.BooleanField(default=False, db_column='edificio_editorial')),
                ('piso', models.CharField(max_length=10, null=True, db_column='piso_editorial')),
                ('departamento', models.CharField(max_length=10, null=True, db_column='departamento_numero_casa_editorial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
