# Generated by Django 5.2.6 on 2025-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id_editorial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(max_length=100)),
                ('pais_editorial', models.CharField(max_length=50)),
                ('calle_editorial', models.CharField(max_length=100)),
                ('numero_calle_editorial', models.IntegerField()),
                ('casa_editorial', models.BooleanField(default=False)),
                ('edificio_editorial', models.BooleanField(default=False)),
                ('piso_editorial', models.CharField(max_length=10)),
                ('departamento_numero_casa_editorial', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
    ]
