# Generated by Django 5.2.6 on 2025-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('numero_calle', models.IntegerField()),
                ('casa', models.BooleanField(default=False)),
                ('edificio', models.BooleanField(default=False)),
                ('piso', models.CharField(max_length=10)),
                ('departamento_numero_casa', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
