# Generated by Django 5.2.6 on 2025-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('nombre_autor', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
        ),
    ]
