import sqlite3, json, os
p=os.path.join(os.path.dirname(__file__),'..','db.sqlite3')
p=os.path.normpath(p)
print('DB:', p, 'exists?', os.path.exists(p))
conn=sqlite3.connect(p)
cur=conn.cursor()
cur.execute("SELECT id, app, name, applied FROM django_migrations WHERE app='prestamos'")
rows=cur.fetchall()
print('before rows:', rows)
backup=os.path.join(os.path.dirname(__file__),'django_migrations_prestamos_backup.json')
with open(backup,'w') as f:
    json.dump([{'id':r[0],'app':r[1],'name':r[2],'applied':r[3]} for r in rows], f, default=str)
print('backup saved to', backup)
cur.execute("DELETE FROM django_migrations WHERE app='prestamos' AND name!='0001_initial'")
conn.commit()
cur.execute("SELECT id, app, name, applied FROM django_migrations WHERE app='prestamos'")
rows2=cur.fetchall()
print('after rows:', rows2)
conn.close()
